Arksine/moonraker

docs/installation.md
moonraker/plugins/power.py
scripts/moonraker-requirements.txt

Adding plugin to control printer power via shell scripts. This would allow moonraker to turn on/off the printer rather than manually doing it through the cli. Implementing this into moonraker rather than klipper since if a MCU is powered down, due to a power off, klipper will refuse to issues any commands such as M80/M81 which would allow the MCU to turn back on if controlled by hardware.

Printer power plugin

---

docs/installation.md
docs/web_api.md
moonraker/app.py
moonraker/moonraker.py
moonraker/plugins/file_manager.py
moonraker/websockets.py
test/client/index.html
test/client/js/main.js

This pull request extends the file manager so config files can be downloaded, modified, and uploaded.  Included files must be in a directory specified by the [moonraker] configuration option `config_include_path`.  
Client developers should be aware that the behavior of "notify_filelist_changed" has been altered.  It no longer sends a filelist with the event, clients can decide if the need to retrieve an updated list or not.  Clients will receive an  object with"action", "filename", and "root" attributes.  For file move/or copy, they will receive a "prev_file" attribute in addition to the others.  Changes to the existing API as well as the configuration endpoints have been added to web_api.md.
Signed-off-by:  Eric Callahan <arksine.code@gmail.com>

file_manager:  Add support for serving configuration files

---

docs/web_api.md
moonraker/plugins/file_manager.py
test/client/index.html
test/client/js/main.js

This PR looks to resolve an overly complex system for managing printer configuration files.  It is no longer possible to access printer.cfg if it is located outside of the "config_path" specified in Moonraker's configuration.  
Given these changes, the endpoints for accessing config files have changed:
- Files in the configured file path can be accessed at `/server/files/config/<filename>` (vs the previous `/server/files/config/include/<filename>`).   This applies both to config file downloads and config file deletions.
- Config examples can be accessed at `/server/files/config_examples/<filename>`.  The "config_examples" root is read-only, it is not possible to delete, upload, or copy to, or move from this path.  It is however possible to copy a file from the "config_examples" root to …

file_manager:  rework config file management

---

docs/api_changes.md
docs/web_api.md
moonraker/app.py
moonraker/authorization.py
moonraker/plugins/file_manager.py
moonraker/plugins/klippy_apis.py
moonraker/plugins/machine.py
moonraker/plugins/power.py
moonraker/plugins/temperature_store.py
moonraker/websockets.py
test/client/js/main.js

This pull request changes how websocket APIs are generated.  The goal is to eliminate ridiculous API calls such as `get_printer_query_endstops_status`.  That example would now resolve to `printer.query_endstops.status`.  This also ensures that  APIs registered by Moonraker are contained within a namespace, eliminating the chance that an endpoint added from Klipper can cause a conflict.
@jordanruthe This also changes the APIs for the power plugin.  Specifically, rather than put it in the `/printer` path, the APIs are now located at `/machine/gpio_power`, so for example `GET /machine/gpio_power/devices` or `machine.gpio_power.devices`.  I did this for the reason above, it is possible that Klipper could one day have its own "power" extra.  I don't see that happening, but if it does this …

api:  clean up websocket API

---

scripts/install-moonraker.sh

If Klipper is installed as systemd service, the script would fail and exit at step 6 (corrected that typo) when trying to stop Klipper via init.d. Changing the used command to systemctl will be compatible with both init.d and systemd services.

fix: make installer not fail if klipper is installed as systemd service

---

moonraker/plugins/power.py

I am using CLI to turn on/off my printer, so I decided to integrate it into moonraker (and, in the process, mainsail).
I have also added new `/machine/power/{action}` endpoints, because now it's not just `gpio_power` devices.

power:  make the plugin more modular

---

docs/api_changes.md
docs/web_api.md
moonraker/app.py
moonraker/authorization.py
moonraker/moonraker.py
moonraker/plugins/data_store.py
moonraker/plugins/file_manager.py
moonraker/plugins/klippy_apis.py
moonraker/plugins/machine.py
moonraker/plugins/power.py
moonraker/websockets.py
test/client/js/main.js

This makes several changes to the code with the goal of making client subscriptions independent.  The changes here will affect both client developers and plugin developers, which is why this was not pushed directly to master.  I plan to wait a few days until this is merged.
For client developers:
- A new `server.websocket.id` API has been added.  This returns a unique ID that moonraker uses to identify different client connections.  It is unlikely that most of you will need this, currently it is only necessary when using the HTTP `POST /printer/objects/subscribe` API.  If you are using that, see the updated documentation for how to include it.
- As mentioned in the intro, the behavior of subscriptions has changed.  Clients will no longer receive a "superset" of all subscribed objects, …

moonraker:  report subscription updates on a per client basis

---

README.md
docs/api_changes.md
docs/installation.md
docs/user_changes.md
docs/web_api.md
moonraker/confighelper.py
moonraker/moonraker.py
moonraker/plugins/power.py
scripts/install-moonraker.sh
scripts/moonraker-requirements.txt
test/client/js/main.js

This is a significant refactor of the power plugin two accomplish two goals:
- Switch from sysfs to libgpiod gpio management
- Implement native support for tplink smartplug devices
The first solves several potential issues that lingered with sysfs managment.  Using libgpoid gives moonraker exclusive access to a gpio and it automatically releases the line if moonraker restarts or stops.  When a gpio is set using libgpoid it is no additional query is necessary to determine if the operation was successful.  This makes behavior consistent, however users should be aware that restarting moonraker will likely result in connected devices powering off.
This change has introduced additional dependencies that require Moonraker be reinstalled and the virtualenv be rebuilt.  As such, new options have …

power:  use libgpiod, add support for tplink-smartplug

---

docs/installation.md
moonraker/plugins/power.py

Based on the TPLinkSmartPlug, I added a power plugin for Tasmota switches. Switching the plug from fluidd works with the power macros from the documentation and it works in fluidd's Power menu to toggle the device.
Since this is the first time I'm working with Tornado/async, I'm happy to get feedback. Also, there is a bit of code duplication, this could probably be improved if additional power plugins are added in the future as well.
Signed-off-by:  Matthias Neumayr matt.neumayr@gmail.com

Tasmota power plugin

---

moonraker/plugins/data_store.py

As presented in #66, add the pwm output to temperature_store to make it available downstream. Now with a proper commit message! Sorry about the closing the previous PR, I'm a bit daft about how to change an already pushed commit message.

Add Klippers heater PWM value to /server/temperature_store

---

docs/configuration.md
docs/web_api.md

Fixes a small technically incorrect wording in configuration.md and web_api.md. G-code files are uploaded to a moonraker instance and not to a mainsail instance.

docs: fix incorrect wording. 'mainsail' should correctly read 'moonraker'

---

docs/configuration.md
moonraker/plugins/power.py

Adds HomeSeer control
Example config:
```
[power printer]
type: homeseer
address: homeseer.local
device: 42
user: admin
password: abcdefgh
```

power: Add HomeSeer control

---

moonraker/components/power.py

Just a couple changes to add support for TP-Link power strips to the power component module. Tested on two separate KP303 power strips. Works the same as the octoprint plugin by adding a `/#` at the end of the IP address to define which "child" you are assigning.

Added support for TPLinkSmartPlug multi plug devices

---

moonraker/components/power.py

add a check and handle consequently in case tasmota device is only one relay and would return a power value when asked a power1 value
Fixes #134 
Signed-off-by:  Arnaud Schaer <arnaud.schaer@wanadoo.fr>

power.py: fix issue with single relay tasmota

---

docs/web_api.md
moonraker/components/history.py

This improves history API:
1. By default returns items in a reverse order (as you expect newest at top)
2. Optimises a search procedure to define a lower and upper boundary assuming that `cached_job_keys` is `order asc`
I noticed this bug when looking at [fluidd](https://github.com/cadriel/fluidd) implementing history API.

Extend history API with reverse order (by default)

---

docs/configuration.md
moonraker/components/power.py

Adds a timer parameter to shelly and tasmota integration.
Use case: 3D printer mains power is connected to one of these devices. 
Just turning off the smart switch will kill power to the RaspberryPI. 
Adding a timer will allow the PI to shutdown cleanly before killing the power.
Example for Shelly:
printer.cfg
```
[idle_timeout]
timeout: 1800
gcode:
TURN_OFF_MOTORS
TURN_OFF_HEATERS
LIGHT_OFF
UPDATE_DELAYED_GCODE ID=delayed_printer_off DURATION=60
[gcode_macro POWER_OFF_SHELLY]
gcode:
{action_call_remote_method("set_device_power", device="shelly_plug", state="on")}
[gcode_macro POWER_OFF_PRINTER]
gcode:
POWER_OFF_SHELLY
{action_call_remote_method("shutdown_machine")}
[delayed_gcode delayed_printer_off]
initial_duration: 0.
gcode:
{% if printer.idle_timeout.state == "Idle" %} …
```

power.py add parameter timer

---

scripts/extract_metadata.py

This should fix an issue where the total filament of g-code files generated by ideaMaker is not parsed correctly and therefore can't be displayed by clients.
For testing purposes, here an example g-code created by ideaMaker 3.6.1.
[ideamaker_3.6.1.gcode.zip](https://github.com/Arksine/moonraker/files/6290062/ideamaker_3.6.1.gcode.zip)

extract_metadata: assign correct data parameter

---

scripts/extract_metadata.py

There was a request of adding filament weight as an additional key for clients to work with as can be seen here: https://discord.com/channels/758059413700345988/826580737154089051/829425183168135189
A new key `filament_weight_total` was defined clients can access.
Supports G-Code from:
- PrusaSlicer
- SuperSlicer
- Slic3r
- Simplify3D
- ideaMaker
- Cura
**Note:**
Cura offers a special placeholder for the filament weight that was used here.
This requires the user to have a specific comment in the start g-code section defined:
`;Filament weight = {filament_weight}`
**Client developers should mention this requirement in their documentation.**
---
Additional change:
- Added parsing of `filament_total` for Slic3r

extract_metadata: parse filament_weight_total

---

moonraker/components/power.py

As pointed out in #146, when having a timer set up for a Shelly power device, its behavior can be a bit weird.
For instance, if the device is off and one turns it on, the timer kicks in after a defined time and turns the device back off. This is probably not desirable when said power device controls the printer itself.
That's why the Shelly device now ignores the timer when the state is being set to _on_.
If applied in its simplest form however, my fix exposes a different issue: when powering off with a timer, the device responds with an "on" state anyway, so the client (mainsail in my case, what else is there anyway 😄 ) thinks it's still on too, and this state is kept that way until moonraker is restarted.
So I decided to make the Shelly device lie a little bit: If the off timer is …

power: Fix Shelly behavior when a timer is configured

---

docs/api_changes.md
docs/web_api.md
moonraker/components/file_manager.py
scripts/extract_metadata.py
scripts/moonraker-requirements.txt
test/client/js/main.js

This is a proposal to add support for inotify events to Moonraker.  This amounts to a significant refactoring of the file_manager, so I want to slow roll merging this PR, with the option to abort if we feel that it could cause significant issues. 
From the Client API perspective the changes are rather mild, and mostly pertain to the `notify_filelist_changed` notification.  Specifically the actions have changes, as some of the exisiting actions do not make sense when dealing with inotify.  The [api_changes.md](https://github.com/Arksine/moonraker/blob/17f9eff89d13db9af11b958fda3b5b6d09a49ad5/docs/api_changes.md) document in this PR contains details on all the API changes in this pull request.  It may also be useful to look at the diff of `web_api.md`. 
As mentioned in the linked …

file_manager:  add support for external file events via inotify

---

moonraker/components/power.py

My Home Assistant instance only uses https, and the existing code was hardcoded to http.
Added https support, and fixed a bug where it was expected Home Assistant would provide an updated status, but actually returns an empty body

Fix Home Assistant https support

---

moonraker/components/history.py

Adds a support for `cancelled` state introduced by https://github.com/KevinOConnor/klipper/pull/4366.
Related:
- https://github.com/KevinOConnor/klipper/pull/4366
Signed-off-by: Kamil Trzcinski <ayufan@ayufan.eu>

history: add support for cancelled state

---

docs/configuration.md
moonraker/components/power.py

Phillips Hue exposes all switches to the "lights" domain on home assistant, that doesn't work with the current implementation as that is hard-coded to the "switch" domain. 
I added a small change to allowing changing to other domains but keep "switch" the default.

Add support for different types of homeassistant switches

---

moonraker/components/klippy_apis.py

This switches Moonraker from calling `CANCEL_PRINT` and alikes
to rather use `pause_resume/` API that underneath calls
the relevant G-Codes.
This done, this way, allows Klipper to be able to interrupt
blocking operations gracefully.
Related:
- https://github.com/KevinOConnor/klipper/pull/4398
- This makes `Cancel of a print` (when called via API) to be immediate when during a heating phase
Signed-off-by: Kamil Trzcinski <ayufan@ayufan.eu>

pause_resume: Make Moonraker to use `pause_resume/*` API

---

docs/example-home-assistant.yaml

This cleans up the Home Assistant integration example a bit, adding icons and making sure that no templating errors are shown on the logs if it fails to call moonraker for any reason.

docs: Refactors the Home Assistant example

---

docs/example-home-assistant.yaml

There was a minor issue with the Home Assistant template related to the priority of Jinja expressions (filters seem to take precedence over operations), so it would show "progress: 1.234567%" instead of "progress: 1.2%".

Fixes rounding issue in home assistant sensor

---

moonraker/confighelper.py

this is a suggestion for a better understandable message for invalid option warnings

confighelper: update 'Invalid config option' warning

---

docs/example-home-assistant.yaml

Small example showing how to add a switch in Home Assistant that will allow users to control the power of devices configured in the `[power]` sections of moonraker.

Adds Home Assistant power switch example

---

docs/configuration.md
moonraker/components/power.py

This adds support for 433Mhz RF transmitters (i.e. for wireless sockets like [this](https://de.aliexpress.com/item/1005002291642865.html) one) to switch on/off devices.
It duplicates some code from the gpio device to configure the pin. This could be done in a base class instead to remove the code duplication. Let me know if this is desired.

Adding support for 433Mhz RF transmitter as power devices

---

docs/web_api.md

credits to meteyou who spotted it
Signed-off-by: Christoph Frei <fryakatkop@gmail.com>

docs: fix typo in web_api.md

---

docs/configuration.md
docs/web_api.md

Ensures all Fluidd repo references are pointing to the new org-based address.

docs: updates to new Fluidd repo address

---

README.md
docs/configuration.md
docs/user_changes.md
docs/web_api.md
moonraker/components/file_manager/file_manager.py
moonraker/components/history.py
moonraker/components/job_queue.py
moonraker/components/job_state.py
moonraker/components/klippy_apis.py
moonraker/components/machine.py
moonraker/components/mqtt.py
moonraker/components/paneldue.py
moonraker/components/power.py
moonraker/components/update_manager/update_manager.py
moonraker/eventloop.py
moonraker/moonraker.py

This primary purpose of the Pull Request is to provide central documentation for the new `job_queue` component, along with changes made to Moonraker to accommodate it.  When implementing the job_queue I came across several potential issues that required refactoring some parts of the core server.  Those changes will be outlined below.
Two new core modules are added, `job_state` and `job_queue`.  The `job_state` module is primarily of interest to Moonraker developers.  Its purpose is to process Klipper's `print_stats` module, determine changes in print state, and fire off events in response.  The result is a reduction in duplicated code, as it is likely that several Moonraker components will need to react to changes in print state.  The `history` module has been refactored to use the …

job_queue: a FIFO queue for G-Code print jobs

---

docs/configuration.md

Comparing to mqtt I think it should be H3 to appear in the index
Signed-off-by:  Richard Mitchell <richardjm+moonraker@gmail.com>

wled: fix index for wled

---

moonraker/components/mqtt.py

I've seen quite a few times this error with MQTT on my production instance:
Here's the output from moonraker's `/server/info`:
```json
{
"result": {
"klippy_connected": true,
"klippy_state": "ready",
"components": [
"database",
"file_manager",
"klippy_apis",
"machine",
"data_store",
"shell_command",
"proc_stats",
"job_state",
"job_queue",
"authorization",
"octoprint_compat",
"history",
"update_manager",
"gpio",
"power",
"mqtt"
],
"failed_components": [
"mqtt"
],
"registered_directories": [
"config",
"logs",
"gcodes",
"config_examples",
"docs"
],
"warnings": [
"Component 'mqtt' failed to load with error: [Errno -3] Temporary failure in name resolution"
],
"websocket_count": 1,
"moonraker_version": "v0.7.1-152-gdf18928-dirty"
}
}
```
I realized that this is just a temporary error, possibly …

mqtt: retry connection if failed to resolve hostname

---

docs/web_api.md
moonraker/components/machine.py

Adds the property "serial_number" to the cpu info structure.
Adding this property gives us a persistent unique id that allows better integration into Home Assistant (something else I am working on at the moment).

machine: add serial number attribute for cpu

---

docs/configuration.md
moonraker/components/zeroconf.py
scripts/moonraker-requirements.txt

Enable Zeroconf service registration allowing external services to more easily detect and use Moonraker instances.
Example of the service announcement:

zeroconf: add module for zeroconf discovery

---

docs/configuration.md

Signed-off-by:  Travis Collins <travistx@gmail.com>
I am using Home Assistant with https, and had a difficult time getting the  moonraker`[power]` configuration working with this. Eventually I read through the code and discovered this undocumented [protocol](https://github.com/Arksine/moonraker/blob/ccb86ea039bf1309b9fd4bb520a29bdb3af2bf36/moonraker/components/power.py#L381) config option, which worked great! Adding it to the documentation for future travelers.

docs: document the protocol config option

---

docs/configuration.md
moonraker/components/file_manager/file_manager.py
moonraker/components/file_manager/metadata.py
scripts/moonraker-requirements.txt

This enables support processing gcode files with object tags using the `postprocess-cancellation` module.  The primary differences between this approach an PR #281 are as follows:
- Metadata is parsed first.  At the time of metadata parsing Moonraker will determine if the gcode file has object tags.  If the file has tags and object processing is enabled the file is passed to the `preprocessor` after metadata extraction is complete.
- The `file_manager` checks for duplicate `create_file` notifications and discards them.  This prevents duplicate `create_file` events that occur when the processed file overwrites the original gcode.
I have tested this with PrusaSlicer.  This PR still needs testing with Cura and Ideamaker, however I expect that they should work correctly.
Another thing to note …

file_manager: add support for object processing

---

docs/example-home-assistant.yaml

Currently the file makes no mention of any type of auth, so I've added a short example with an explanation of when you should use it.
Signed-off-by:  Rafael Schridi <r.schridi@gmail.com>

Add API key info to example-home-assistant.yaml

---

scripts/moonraker-requirements.txt

This fixes a bug that caused retraction moves to be included in bounding box calculations.
Before:
After:

Bump preprocess-cancellation to 0.1.6

---

moonraker/components/file_manager/metadata.py

This PR will add parsing of 3 new, optional metadata types for:
- PrusaSlicer and it's derivatives
- Simplify3D
- Cura
- IdeaMaker
Those types are:
* Nozzle diameter
* Filament type
* Filament name
Note: As far as i am aware Simplify3D does not provide any info about the filament type. At least i didn't find anything during research and testing. So in case of Simplify3D, this PR will only provide filament name and nozzle diameter.
For Cura and IdeaMaker it is necessary to add a custom start g-code comment because they do not output the requested metadata to the g-code file by default. But they do provide internal placeholder variables for those values. The required lines for the start g-code are as follows (it is important to have the exact syntax as shown) :
Cura:
```
;Nozzle diameter = …
```

metadata.py: add more metadata

---

moonraker/components/file_manager/metadata.py

This PR will improve a method previously introduced by #322.
IdeaMaker already exports the nozzle diameter, so using a custom g-code comment is obsolete. The new regex pattern extracts the natively exported nozzle diameter.
Signed-off-by: Dominik Willner <th33xitus@gmail.com>

metadata.py: fix parsing of IdeaMaker nozzle_diameter

---

docs/configuration.md
moonraker/components/wled.py

- For mobile printers such as Voron 0.1 having to reconfigure wifi in each location is a pain
- In the 0.13 release (still in beta) direct serial communication was added - and seems to work very nicely
Signed-off-by:  Richard Mitchell <richardjm+moonraker@gmail.com>

wled: Add serial support for direct communication

---

docs/configuration.md
moonraker/components/power.py

The added option allows to delay switching off a power source after klippy shuts down. This is useful when controlling the printer power through moonraker: In case klipper shuts down, the printer won’t be turned on indefinitely, but it will also have time to cool down the extruder before the fans are turned off.

power: add 'off_when_shutdown_delay' option

---

docs/configuration.md
moonraker/components/power.py

Added support for smartthings switch in power.py.
Added documentation to configuration.md.
I understand that changes to implementation of power over HTTP will change in the near future.  So, feel free to reject based on that.
Signed-off-by: Mitch Gallman <mitchell.gallman@gmail.com>

power: add support for smartthings switch

---

docs/configuration.md
docs/moonraker.conf
docs/user_changes.md
moonraker/components/octoprint_compat.py

Now reading configs from moonraker.conf file, octoprint_compat section. Values are set to the defaults that were previously hardcoded and reflected in the sample moonraker.conf file.

Implemented config-based webcam settings for Cura

---

README.md
docs/web_api.md

also includes:
* readme: replace `Meteyou` with `Mainsail-Crew`
* docs: replace `meteyou` with `mainsail-crew` in web_api.md
Signed-off-by: Dominik Willner <th33xitus@gmail.com>

readme: fix link for MainsailOS

---

docs/configuration.md
moonraker/components/notifier.py
scripts/moonraker-requirements.txt

This component will be a bridge between moonraker and https://github.com/caronc/apprise. This way users can easily add all kind of notification services to their printer. 
Each notifier can subscribe to events.
- completed
- started
- error
- canceled
```ini
[notifier my_personal_discord]
events: started,completed
url: https://discord.com/api/webhooks/{id}/{secret}}
body: Printer update: '{event_name}'
[notifier print_start]
url: tgram://{bottoken}/{ChatID}
events: started
body: Your printer started printing '{event_args[1].filename}'

notifier: create the new notifier component 

---

docs/configuration.md
moonraker/components/notifier.py

There is a typo in `job_state:completed`. Should be `job_state:complete`.

[bugfix] notifier: typo at `job_state:completed`

---

docs/configuration.md
moonraker/components/notifier.py

This adds support for the `attach` property that is available to numerous notification services.

notifier: add support for 'attach' property

---

docs/configuration.md

There was a small typo left after the recent 'completed' bugfix.

docs: fix an incorrection in the notifier example

---

docs/web_api.md

Fixes a typo in the [websocket identify RPC request](https://github.com/Arksine/moonraker/blob/efeea0d8e1d84e8201997a58c58274c79d8601b2/moonraker/websockets.py#L282)

docs: fix incorrect identify method

---

docs/configuration.md
docs/web_api.md
moonraker/components/wled.py

For the "Percent" preset the intensity controls the amount of the bar lit up 0-100
Work around issue when preset is re-enabled if sending intensity or speed while no preset is active
Signed-off-by:  Richard Mitchell <richardjm+moonraker@gmail.com>

wled: Add extra control for wled effects

---

moonraker/components/authorization.py

This might be best configurable, but browsers are blocking requests from public to
private networks (e.g. public IP address spaces to 192.168.x-like private spaces)
In the future, an `Access-Control-Request-Private-Network` header will be sent with
these requests, and servers must respond with `Access-Control-Allow-Private-Network`.
This PR adds basic support for this response header. To test this feature, you will
need to set the following options in chrome://flags:
chrome://flags/#block-insecure-private-network-requests - Disabled
chrome://flags/#private-network-access-send-preflights - Enabled
chrome://flags/#private-network-access-respect-preflight-results - Enabled
This will start with the next Chrome version (104), and Mozilla has marked the
standard as "worth prototyping", which …

Enable CORS Private Network access

---

docs/installation.md
scripts/install-moonraker.sh

Also allow setting defaults for installation command line
flags from the environment
```sh
MOONRAKER_VENV=$HOME/.venvs/moonraker \
MOONRAKER_REBUILD_ENV=y \
MOONRAKER_FORCE_DEFAULTS=n \
MOONRAKER_DISABLE_SYSTEMCTL=n \
MOONRAKER_CONFIG_PATH=$HOME/printer/moonraker.conf \
MOONRAKER_LOG_PATH=/tmp/moonraker.log \
./scripts/install-moonraker.sh
```
Personally, I set `MOONRAKER_VENV` and `MOONRAKER_CONFIG_PATH` in my .profile
Signed-off-by: Franklyn Tackitt <git@frank.af>

Allow configuring the virtualenv location

---

scripts/set-policykit-rules.sh

Polkit changed its versioning scheme starting with version 121 (the preceding version was 0.120) causing set-policykit-rules.sh to fail.

Following polkit versioning scheme change

---

moonraker/components/file_manager/metadata.py

Adds Chamber Temp metadata reading for all slicers with these exceptions:
- Kiri:Moto: chamber temp doesn't seem to be supported by the slicer
- Simplify3D: I don't have a license, so no idea how to add this one

metadata: adds chamber temp support

---

docs/configuration.md
moonraker/components/notifier.py

This way you can create macros that can be used to notify services through gcode.
Example:
```ini
[gcode_macro NOTIFY_FILAMENT_CHANGE]
gcode:
{action_call_remote_method("notify",
name="telegram",
message="Filament change needed!")}
```
The body is overridable. 
Let me know what you think of this. Happy to receive any feedback.

notify: add ability to notify using a remote method

---

moonraker/components/proc_stats.py

This PR exposes additional network stats to the /machine/proc_stats endpoint.
They are helpful for troubleshooting network issues, especially when using a CanBus network. 
```
user@hostname:/opt/moonraker $ curl -s localhost:7125/machine/proc_stats | jq '.result.network.wlan0'
{
"rx_bytes": 168137592,
"tx_bytes": 40569317,
"rx_packets": 177732,
"tx_packets": 104178,
"rx_errs": 0,
"tx_errs": 0,
"rx_drop": 0,
"tx_drop": 0,
"bandwidth": 1630.96
}
user@hostname:/opt/moonraker $ curl -s localhost:7125/machine/proc_stats | jq '.result.network.can0'
{
"rx_bytes": 2198209,
"tx_bytes": 3765756,
"rx_packets": 347331,
"tx_packets": 565789,
"rx_errs": 0,
"tx_errs": 0,
"rx_drop": 0,
"tx_drop": 0,
"bandwidth": 1234.07
}
```
Signed-off-by: Rogerio Goncalves <rogerlz@gmail.com>

proc_stats: expose network packets, errors and drops

---

moonraker/components/file_manager/metadata.py

Bambu Studio is a slicer developed by Bambulab.
It's forked from Prusa Slicer. 
It has some cool features like tree support and enhanced overhang performance.
Their repo: https://github.com/bambulab/BambuStudio
I made a customized version from it so it can be used on Voron and other Klipper-based machines.
See the repo here: https://github.com/SoftFever/BambuStudio-SoftFever/releases/tag/v1.1
This PR adds support to extract thumbnails from the g-code files generated by it.

Add support to extract metadata from g-code files generated by Bambu Studio

---

moonraker/components/file_manager/metadata.py

Trim any delimiting quotes from metadata strings.
I know we could just update the regular expressions to do this, but seems easier (and safer!) to just trim the quotes after finding the values.
Here's an example from a Prusa Slicer sliced file showing the problem:

metadata: strip delimiting quotes in strings

---

moonraker/app.py

Allows the fetching of JPEG files without authorization.
Fixes https://github.com/fluidd-core/fluidd/issues/849, https://github.com/mainsail-crew/moonraker-timelapse/issues/56

app: add jpg files to AUTHORIZED_EXTS

---

.gitignore
docs/configuration.md
docs/installation.md
docs/moonraker.conf
docs/user_changes.md
docs/web_api.md
moonraker/app.py
moonraker/assets/welcome.html
moonraker/components/database.py
moonraker/components/file_manager/file_manager.py
moonraker/components/machine.py
moonraker/components/power.py
moonraker/components/secrets.py
moonraker/components/simplyprint.py
moonraker/components/update_manager/app_deploy.py
moonraker/components/update_manager/base_config.py
moonraker/components/update_manager/base_deploy.py
moonraker/components/update_manager/git_deploy.py
moonraker/components/update_manager/update_manager.py
moonraker/klippy_connection.py
moonraker/moonraker.py
scripts/finish-upgrade.sh
scripts/install-moonraker.sh

This pull request will significantly change how file paths are configured.  There are two primary goals: 
1) Clean up the somewhat disjointed way Moonraker's file paths are organized
2) Reduce "worst case scenarios" should an instance be compromised by a malicious actor
As things stand today, a compromised system could have their config and/or gcode paths reconfigured.  This pull request organizes all of Moonraker's into a single data folder, named `$HOME/printer_data` by default.  The folder is organized something like the following:
```
/home/pi/printer_data
├── backup
│   └── 20220822T202419Z
│       ├── config
│       │   └── moonraker.conf
│       └── service
│           └── moonraker.service
├── certs
│   ├── moonraker.cert (optional)
│   └── moonraker.key (optional)
├── config
│   …
```

Rework file path organization and configuration

---

docs/web_api.md
moonraker/assets/welcome.html
moonraker/components/machine.py

Currently Moonraker asks for "root request" and the "root password".
That could be misleading in a way, that users might think moonraker wants access to the root user account (UID 0).
This PR rephrases the terms to "Sudo password" and "sudo" respectively. It also fixes another typo.
It might be a bit nitpicking and i am fine with this PR getting declined. 
Signed-off-by: Dominik Willner <th33xitus@gmail.com>

Suggestion: use term "sudo" instead of "root"

---

moonraker/components/update_manager/app_deploy.py

an user on discord reported this error:
```
[update_manager client KlipperScreen]: Option 'restart_action: KlipperScreen' contains an invalid value 'KlipperScreen'. All values must be one of the following choices: ['client KlipperScreen', 'klipper', 'moonraker']
```
> My machine does not have a restart_action in Moonraker config 
so i concluded that `restart_action` must have been the name during development and the error warning was not updated.

update_manager: fix error message displaying the wrong option

---

docs/web_api.md
moonraker/components/notifier.py

notify: add server endpoints for notifiers to list and test them

---

moonraker/components/update_manager/git_deploy.py

I'm playing with using git submodules to track my entire printer config,
and moonraker only works with separate clones as is. Using `.exists()`
instead of `.is_dir()` allows moonraker to control the submodules.

Git submodules use a .git file instead of a directory

---

docs/configuration.md

The internal variable is called `min_`, but the config option is called `minimum_`.
Signed-off-by: Jim C K Flaten <jckf@jckf.no>

docs: Correct `minimum_event_time` example

---

docs/configuration.md
moonraker/components/ldap.py

This allows for more advanced integration of LDAP databases that are not covered by the default behaviour of is_active_directory.
Signed-off-by: Nick Douma <n.douma@nekoconeko.nl>

ldap: Add option to use a customer LDAP query for looking up the user logging in

---

moonraker/components/file_manager/file_manager.py

The /server/files/directory endpoint allows enumerating all files even in reserved folders marked as not readable because only accessibility of the folder on the filesystem is checked.
I created a small extra component to keep Mainsail from drilling down my .git subfolders in the klipper_config and other folders where it isn't supposed to stick its nose in, by adding those folders as reserved paths, but even then Mainsail would recursively fetch info on each and every file in those folders (see [this Mainsail issue](https://github.com/mainsail-crew/mainsail/issues/1141)).
I think Moonraker allowing this access is a bug and hope that this PR is accepted to address this (as far as my limited knowledge on the ins and outs of Moonraker allow me to propose).

file_manager: disallow drilling down protected folders

---

scripts/moonraker-requirements.txt

Updates streaming-form-data to Version 1.11.0 to be compatible with Python 3.11.0
Signed-off-by: Markus Küffner <kueffner.markus@gmail.com>

scripts: update streaming-form-data dependency

---

docs/configuration.md
moonraker/components/machine.py

Signed-off-by: mirokymac <toufubomb@gmail.com>
Add supervisord to the service provider. 
As supervisord is used as the service manager in containers, this commit is looking forward to populating the service manager of klipper-moonraker container.

machine.py: add support for supervisord service management

---

moonraker/components/simplyprint.py

Put prod. endpoint as the default WS endpoint, + change of API endpoint.
Ready for release tomorrow (the 21st).

Prepare for SimplyPrint release

---

moonraker/components/machine.py

I believe this this get should use `virt_identifier`, not `virt_id`.
Before:
After:

machine: use virtualization.virt_identifier property

---

docs/web_api.md
moonraker/components/job_queue.py

Adds a new optional `reset` Boolean parameter to the POST endpoint of the `job_queue` component, allowing to clear the job queue before adding the new filenames.
Resolves #382

job_queue: add "reset" parameter to post endpoint

---

docs/configuration.md
moonraker/components/mqtt.py

This change allows the user to choose the strategy for publishing klipper states to MQTT.  The original strategy where all state updates are published to a common topic is still the default, but can be turned off using the "publish_combined_status" config option.
The newly added strategy is publishing individual state updates to separate mqtt topics.  It is disabled by default, and can be enabled with the "publish_split_status" config option.
Both strategies can be used together.
Example - when the "heater_bed" attribute "temperature" is published:
publish_combined_status (the existing strategy) publishes a payload similar to:
{"eventtime": timestamp, "status":{ "heater_bed": {"temperature": 55.00}}}
to {instance_name}/klipper/status.  There may be other values in the status key. …

mqtt: add option to publish states to individual mqtt topics

---

scripts/moonraker-requirements.txt

Bumps the apprise version to v1.2.1
Changelog:  
https://github.com/caronc/apprise/releases/tag/v1.2.1

notify: bump apprise to v1.2.1

---

moonraker/components/machine.py

I'm adding support for Moonraker / Mainsail / Fluidd to OctoEverywhere.com! My plugin is almost ready for early testing; things are looking great.
This simple PR allows the "services" UI to show the OctoEverywhere service.

Adding OctoEverywhere.com as a default allowed service.

---

docs/configuration.md
moonraker/components/authorization.py
moonraker/components/power.py

Added the ability to control entire Hue device power groups in addition to controlling Hue devices individually. This can be advantageous if you have several Hue lights in the area of the printer that you would like to control all together.

Added ability to control hue device groups in power.py

---

docs/api_changes.md
docs/configuration.md
docs/web_api.md
moonraker/components/sensor.py

This feature implements a sensor component that can be used to track/log generic sensors from multiple sources. Each sensor can have properties like unit of measurement, accuracy and a display name that help frontends display the tracked measurements.
Some supported sources could be locally connected I2C, SPI or 1-wire sensors as well as remote sensor providers like MQTT or REST API driven sensor.
Example of the component in use with a ESPHome device connected through MQTT:
```
[sensor.py:component_init()] - Initializing sensor component
[sensor.py:initialize()] - Registered sensor 'Chamber Temperature'
[sensor.py:initialize()] - Registered sensor 'Chamber Humidity'
[sensor.py:initialize()] - Registered sensor 'Power Usage'
[sensor.py:component_init()] - All sensors have been initialized …
```

Feature: Generic sensor support and data logging

---

README.md
docs/contributing.md
docs/index.md
mkdocs.yml

Fixes a couple of typos on the main page and readme file.

docs: fixes minor typos

---

docs/printer_objects.md

Fixes a minor typo in the `gcode_move` section of `print_objects.md`.
`coorinates` becomes `coordinates`

Fixes Minor Typo

---

moonraker/components/machine.py

Adds the RatOS configurator to the default service list in machine.py so future installs of moonraker will allow the ratos configurator service to be managed from frontends.

module: add ratos-configurator to default services

---

scripts/moonraker-requirements.txt

While trying to build a test docker container based on `debian:latest` (at the moment, that's `debian:12`) with Klipper and Moonraker, I get this error message:
The base docker image uses Python 3.11, so I checked, and looking at [lmdb changelog](https://github.com/jnwatson/py-lmdb/blob/master/ChangeLog), it shows a more recent version to support it, and when I used that, the error goes away!
One odd thing is this only happens if I build Klipper before Moonraker... nevertheless, it completely seems to go away if I update the lmdb version, hence this PR!

requirements: bump lmdb to 1.4.1

---

moonraker/components/power.py

There is a feature in the Kasa app that will allow you to change plug index (basically for naming). However, in the power.py there are 2 different methods for retreiving children devices (plugs). If you have the index reordered in Kasa then you will get inconsistent results since those methods for retrieval are not the same. This PR unifies them properly and now they work as intended. Simple change.
Signed-off-by: Rick Marino <rcmarino@gmail.com>

[Bug] Fix for TPLinkSmart Strip Index Changing.

---

docs/configuration.md

Thank you for sharing such a fantastic project. It has made my 3D printer even more convenient.
While reading through the documentation, I came across a section that may have a typo, so I have created this pull request. I would greatly appreciate it if you could review it.

docs: fix typos in docs

---

docs/configuration.md

MainsailOS loads the moonraker.conf from `~/printer_data/config/` 
Source:
[MainsailOS moonraker](https://github.com/mainsail-crew/MainsailOS/tree/develop/src/modules/moonraker/filesystem/home/pi)
[MainsailOS klipper](https://github.com/mainsail-crew/MainsailOS/blob/develop/src/modules/klipper/config#L28)

docs: updated prebuild images config path note to `~/printer_data`

---

moonraker/components/file_manager/metadata.py

metadata : fix extract to work with Ideamaker
Correction of the regex (Replacing the = with one: and adding the filament index for the regex to work) 
Correction du regex (Remplacement du = par un : et ajout de l'index du filament pour que le regex fonctionne)
Signed-off-by: Emmanuel WALDNER <emmanuel.waldner@gmail.com>

[FIX] Update metadata.py to work with Ideamaker

---

docs/configuration.md
moonraker/components/power.py

Some alternative Zigbee bridges (i.e. Phoscon) might be running on non-standard HTTP ports. This PR allows specifying a HTTP port so you can still use the Hue integration for these devices also. 
Committer: wollew

allow specifying HTTP port for Zigbee/Hue

---

.readthedocs.yaml
docs/changelog.md
docs/doc-requirements.txt
docs/src/css/extras.css
docs/web_api.md
mkdocs.yml
moonraker/components/machine.py
moonraker/server.py
moonraker/utils/__init__.py
moonraker/utils/cansocket.py
moonraker/utils/ioctl_macros.py
moonraker/utils/sysfs_devs.py

This pull request adds the ability to query the local machine for the following peripherals:
- Serial Devices, including hardware UARTs
- Connected USB devices
- Video Devices (V4L2 and libcamera)
- Unassigned CAN Nodes running Klipper or Katapult
This is accomplished for the most part using sysfs and IOCTLs.  No external dependencies are added in this PR.  That said, it is necessary for the `python3-libcamera` package to be installed on the system to query libcamera devices.  Since this package is only widely available for RPi OS it can't be added to Moonraker as a system dependency as it would cause standard Debian/Ubuntu installs to fail.  That said, if the module is not available it will not cause an error.
This PR also marks the switch from the "readthedocs" theme to the "material" …

machine: add support for peripheral requests

---

scripts/moonraker-requirements.txt

0.2.1 ensures that the exclude_object markers are the first
non-comment g-code in the files, fixing issues with klipper adaptive
meshing

Bump preprocess_cancellation to 0.2.1

---

docs/configuration.md
moonraker/components/update_manager/update_manager.py

This enables customizing the time of day within which periodic refresh occurs.
Previously docs said it happens between 12am-4am which is misleading, because the code effectively allowed refresh until 4:59:59 AM. The default window is now '0-5', which is practically the same as before.
The comment about checking every 24h hours has been fixed as well. This hasn't been true since commit c4fa76f21792943ea512d24326259f01d2fa7e89

Allow configuring the update refresh window

---

docs/web_api.md

The current example shows `can_uuids` as an array of strings, when in fact this is an array of objects with `uuid` and `application` properties.

docs: corrects canbus peripherals response example

---

moonraker/components/spoolman.py

Closes #841.
As noted in the linked issue, spoolman uses the `x-total-count` header field in its response to indicate the total count, if appropriate, for a pagination result.
To also include this in the proxy I modified the returned JSON of the V2 response to not only return the `response` but also a `response_header` field with all custom headers (Headers starting with `x-`).
I am open to suggestions or alternative ideas on how to handle this change. I feel that adding it as part of the V2 is the safest and will not break any current implementations.

spoolman: Include total count header

---

docs/changelog.md
docs/installation.md
docs/web_api.md
moonraker/common.py
moonraker/components/application.py
moonraker/components/authorization.py
moonraker/components/database.py
moonraker/components/file_manager/file_manager.py
moonraker/components/history.py
moonraker/components/job_queue.py
moonraker/components/klippy_apis.py
moonraker/components/machine.py
moonraker/components/simplyprint.py
moonraker/eventloop.py
moonraker/server.py
moonraker/utils/filelock.py
pyproject.toml
scripts/install-moonraker.sh
scripts/moonraker-requirements.txt
scripts/system-dependencies.json

This series moves Moonraker's underlying database implementation from LMDB to Sqlite3.  This is essentially a rewrite of `database.py` and a significant refactor of `history.py` and `authorization.py`.   As such, I'm creating a pull request for these changes  before merging.   Users should see no difference, Moonraker will convert the existing lmdb database.  Moonraker will not delete the prior lmdb database in the event that a bug is discovered that I missed in testing.
In addition, this should not break frontends, nor should it impact any components using internal APIs.  This is accomplished by creating a `namespace_store` table, which is effectively a key-value store that mimics the way LMDB stores data.
The motivation for this change is several fold:
- LMDB databases are architecture …

database: migrate from lmdb to sqlite3

---

moonraker/components/file_manager/file_manager.py

Hi, I'm the author of Happy Hare - a MMU extension to Klipper.  Happy Hare adds a couple of pieces of functionality to Moonraker, one of which extends the metadata parsing to find and substitute placeholders in the gcode.  E.g. to assess the set of Tools used in a multi-color print.  The issue is that this adds a little extra processing time and the hard coded default of 10s is insufficient.  (I know that if "object processing" is enabled the default jumps to 300s which is a current workaround).
This PR adds the ability to optionally specify the default (minimum) timeout using an extra optional parameters under file_manager:
```
[file_manager]
default_metadata_parser_timeout: 30
```
Which replaces the old default if specified. This can also be used to push object_processing timeout higher …

Allow default metadata parser timeout to be configurable

---

moonraker/components/file_manager/metadata.py

This PR adds support to extract metadata from the g-code files generated by [QIDISlicer](https://github.com/QIDITECH/QIDISlicer).

metadata: Add support to extract metadata from g-code files generated by QIDISlicer

---

docs/external_api/jsonrpc_notifications.md

Fixed the main JSON example that was actually invalid (was missing the containing `{` and `}`)
Reformatted an example for better readability.
Also marked 2 other examples with the new doc tags

docs: fixes invalid JSON in example

---

moonraker/components/file_manager/metadata.py

This is a follow up on PR #962 as I just noticed that the split and then parse uses unbalanced regular expressions (so a string like `"bla;bla";"bla"` will produce `['"bla', 'bla"', '"bla"]` instead of `['"bla;bla"', '"bla"]`)
Regex is kind of a personal challenge, so I took a stab in rewriting the pattern with a balanced one!
The new method will accept values with properly balanced double quotes (including escaped double-quotes) or simple values followed by the separators!
Quotes will be stripped and then all spaces will be trimmed in the resulting values.

metadata: balanced quoted string split

---

moonraker/components/file_manager/metadata.py

Cura is horribly bad in providing metadata on the gcode files, but we can improve the parsing capability a bit by correctly handling `filament_total`, `filament_weight_total`, and `filament_weights`, as all of these are represented in the gcode as arrays!
I tested this myself with a couple of files, here's 2 header examples directly from Cura 5.9:
```text
;FLAVOR:Marlin
;TIME:4493
;Filament used: 0.500757m, 0.502888m, 0m
;Layer height: 0.1
;MINX:67.45
;MINY:66.199
;MINZ:0.3
;MAXX:132.551
;MAXY:133.751
;MAXZ:9
;TARGET_MACHINE.NAME:Unknown
;Generated with Cura_SteamEngine 5.9.1
; Pre-Processed for Cancel-Object support by preprocess_cancellation v0.2.0
; 2 known objects
EXCLUDE_OBJECT_DEFINE NAME=2040_MGN12_guide_stl_1 CENTER=100.947,113.723 …
```

metadata: improves Cura multi-extruder support

---

moonraker/components/power.py

Really minor fix: Moonraker `[power]` component when pointing to a Klipper pin sends 2 spaces instead of a single one, this fixed it:
On that screenshot, the top of is from Moonraker, the bottom one is from Fluidd)

power: removes extra space from command

---

moonraker/components/update_manager/git_deploy.py

found this typo while using fluidd:

fix typos in git_deploy.py

---

moonraker/components/file_manager/metadata.py

This will allow for less common or newly created slicers to attach thumbnails into gcode, without a need to report as being a different slicer.
As for example, OrcaSlicer was one of them in the past:
https://github.com/SoftFever/OrcaSlicer/issues/840#issuecomment-1527428054
I think this feature will be helpful, as `BaseSlicer` already contains all the universal logic for thumbnails, and PrusaSlicer forks won't stop being created.

metadata: allow generating thumbnails for unknown slicer
