Arksine/moonraker

moonraker/plugins/power.py
=> Fixing paths on power plugin

README.md
Added link to klipper in the readme, jut to have all related links in one page :)
=> Added link to Klipper software

docs/configuration.md, moonraker/plugins/power.py
This adds an option to lock a power device while printing. Specifically, it ensures that you cannot turn off the printer while the printer is in a printing state.
=> Add option to lock power device while printing

docs/configuration.md, docs/web_api.md, moonraker/plugins/history.py, moonraker/plugins/update_manager.py
Add module to track print history.
=> Print History

docs/web_api.md
only a url fix in the docs
Signed-off-by: Stefan Dej <meteyou@gmail.com>
=> fix moonraker process stats link

moonraker/app.py
Replace non-ASCII characters with "?" and add escaped unicode version of the file name to the "Content-Disposition" header to fix problems with thumbnails and downloading for the gcode file with non-ASCII characters in filename.
"?" is not the best replace character as it is forbidden character for the filenames on Windows but it is simple and fast solution and anyway this fix is providing Unicode filename that should be used in the modern browsers.
=> app: Fixed download for the files with non-ASCII characters in name.

moonraker/components/file_manager/metadata.py
This commit allows Moonraker to parse thumbnails from g-code files generated by IdeaMaker.
Signed-off-by:  Dominik Willner <th33xitus@gmail.com>
=> metadata: add IdeaMaker thumbnail parsing

docs/web_api.md, moonraker/components/update_manager/git_deploy.py
Add real repository name to the ws msg.
more info see issue #257
=> add real git-repository name to update manager api

moonraker/components/power.py
Fixes #266
I can confirm this is working fine on my RaspberryPi 3B+ running latest RaspiOS (Debian Bullseye), but better to ensure it also works on other systems (FluiddPi, Mainsail OS, ...)
=> power: improves GPIO initial_state handling

moonraker/components/mqtt.py
Implements #262
While we discussed in the FR to have this under the "status" topic, I've gone with a separate "state" topic to ensure it is not overwritten by subsequent messages.
That way, one can check the "state" topic anytime to see if Moonraker is up and running!
=> mqtt: implements last will and testament

README.md, docs/configuration.md, docs/installation.md, docs/web_api.md
Signed-off-by:  Christoph Frei <fryakatkop@gmail.com>
=> docs: change repository links from meteyou to mainsail-crew

docs/configuration.md
=> docs: fixes minor typos

moonraker/components/zeroconf.py
GitHub is for some reason showing the old PR as merge, this is an error, and it won't let me restore so I need to create a new PR: https://github.com/Arksine/moonraker/pull/284
However this implements the latest and greatest approach to getting and updating IP address for the Zeroconf service.
=> zeroconf: Implement new approach for ip detection

.github/workflows/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/ISSUE_TEMPLATE/config.yml, .github/workflows/ISSUE_TEMPLATE/feature_request.yml
=> moonraker: adds GitHub issue templates

scripts/sudo_fix.sh
According to https://github.com/Arksine/moonraker/issues/241
Signed-off-by: Stephan Wendel <me@stephanwe.de>
=> FIX: sudo_fix.sh not working on armbian

docs/configuration.md, docs/dev_changelog.md, docs/installation.md, docs/printer_objects.md, docs/user_changes.md, docs/web_api.md, moonraker/components/mqtt.py, moonraker/components/update_manager/zip_deploy.py, moonraker/moonraker.py, moonraker/utils.py, scripts/build_release.py
=> Fixes minor typo

docs/configuration.md, moonraker/components/power.py
=> power: adds support for Klipper Device

docs/configuration.md, moonraker/components/power.py
Add separate output_id configuration attribute for TPLink Smartplug device.
Signed-off-by:  Matthew Humphrey <mhumphrey@gmail.com>
=> module: power

docs/example-home-assistant.yaml
docs: add Home Assistant camera example
Signed-off-by: Pavel Znamenskiy <[pznamenskii@gmail.com](mailto:pznamenskii@gmail.com)>
=> add Home Assistant camera example

moonraker/components/file_manager/metadata.py
=> metadata: add support for parsing layer count in Cura

docs/configuration.md, moonraker/components/notifier.py
So I can tell when my printer needs my help :D
=> notifier: Add paused and resumed events for notifier component

.github/ISSUE_TEMPLATE/announcement.md
Signed-off-by:  Eric Callahan <arksine.code@gmail.com>
=> github: add an announcement issue template

docs/configuration.md
docs: correct flip_v for webcam vertical flip
Signed-off-by: David Smith <davidosmith@gmail.com>
=> docs: minor typo fix

docs/configuration.md, docs/web_api.md, moonraker/components/authorization.py, moonraker/klippy_connection.py, scripts/moonraker-requirements.txt
add LDAP authentication to moonraker
Signed-off-by: Luca Schöneberg [luca-schoeneberg@outlook.com](mailto:luca-schoeneberg@outlook.com)
=> feat: add LDAP support

docs/web_api.md, moonraker/components/authorization.py
add endpoint to get default authentication source
Signed-off-by: Luca Schöneberg [luca-schoeneberg@outlook.com](mailto:luca-schoeneberg@outlook.com)
=> ldap: add endpoint to get default authentication source

moonraker/components/webcam.py
Signed-off-by: Grant Harding <gharding@gmail.com>
=> webcam: fixed rotation param in api, str -> int

scripts/moonraker-requirements.txt
=> notify: upgrade apprise to version 1.0.0

docs/web_api.md
=> docs: web_api: update allowed system services

docs/api_changes.md
=> docs(api-changes): fix method typo

docs/configuration.md
=> docs: improve notifier reference when using the action

scripts/moonraker-requirements.txt
https://github.com/caronc/apprise/releases/tag/v1.2.0
https://github.com/caronc/apprise/releases/tag/v1.1.0
TLDR: many fixes for existing services and some new services have been added.
=> notify: upgrade apprise to version 1.2.0

moonraker/components/file_manager/metadata.py
This PR adds changed to support the new/changed Metadata for Simplify3D Version five.
For most part this are simple changes where only the "property name" changed slightly.
A bot more involved is the new temperature format, as this is a block of properties that which are grouped together and must be parsed as group.
Closes #571.
=> metadata: Add support for Simplify3D v5

docs/configuration.md, moonraker/components/notifier.py
This lets you format the messages through apprise a little nicer
=> notifier: Add `body_format` as an option

moonraker/components/file_manager/metadata.py
MomentSlicer is fork of OrcaSlicer which is based on Bambustudio and PrusaSlicer
the repo here : https://github.com/MOMENT3D/MomentSlicer/tree/v1.6.6
Signed-off-by: Sanghun Jung / Email: sanghun.id@gmail.com
=> add support for MomentSlicer

docs/configuration.md
Replace PR #732 - commit message amended
=> docs: add Domoticz power device documentation

moonraker/components/simplyprint.py
This is a small patch to the simplyprint component which removes the AI streaming implementation.
=> simplyprint: remove defunct AI functionality

docs/external_api/file_manager.md
Minor typo fix on the JSON example.
=> docs: JSON typo fix

docs/external_api/file_manager.md, moonraker/components/file_manager/metadata.py
This adds a couple more variables that are useful for multi-color prints.
=> file_manager: Added per tool weights and total filament change count

moonraker/components/simplyprint.py
Printers with multiple Klipper versions / implementations are using different fields to provide print progress.
Current implementation only relies on `display_status.progress`. For example, the Anycubic Kobra 3/S1 printers do not use this field.
In order to maintain some consistency with other clients implementation, I reimplemented the same algorithm as Mainsail and Fluidd:
- Mainsail: https://github.com/mainsail-crew/mainsail/blob/6f0f562a0b09ab242f35533b71fa7f99a75e2025/src/store/printer/getters.ts#L37
- Fluidd: https://github.com/fluidd-core/fluidd/blob/d01112461ac49962ca32c8bd4c12d6eec619ac1c/src/store/printer/getters.ts#L123
I also kept current implementation adding a test to make sure all the fields are correctly provided.
This should now be more robust with other printers.
=> Improve SimplyPrint progess calculation mimicing what's being done in Mainsail and Fluidd

moonraker/components/update_manager/git_deploy.py
When a git project managed by moonraker is a submodule of a superproject, gitfile
contains a relative path.
Resolve contents of the gitfile relative to the directory containing the gitfile.
Why the superproject and submodules? Poor man 'restore point', so I can roll back software and configuration to a known-working state.
=> git_deploy: Support relative paths in gitfile

moonraker/components/simplyprint.py
This PR consists of the following changes: 
- Restructered `exclude_object` handling to be sent over `job_info` as `skipped_objects`
- Append and track current job_id in `job_info` and `file_progress` messages
- Fixed old test-url (internal usage)
I decided to open up this PR against master instead of the current working dev-branch to avoid cluttering the repo with 2 PRs, but if we prefer doing it that way that is also fine.
Let me know if any changes are needed!
=> simplyprint: Skip objects functionality
